DROP TABLE IF EXISTS Contenuto_playlist CASCADE;

CREATE TABLE Contenuto_playlist (
    playlist char (10),
    titolo varchar (30),
    album int,
    FOREIGN key (playlist) REFERENCES Playlist(playlist_id),
    FOREIGN key (titolo, album) REFERENCES Canzone(titolo, album)
);

INSERT INTO Contenuto_playlist(playlist, titolo, album) VALUES
    ('XnKB6kBrsk', 'purus', 1),
    ('XnKB6kBrsk', 'vitae', 1),
    ('XnKB6kBrsk', 'ultrices posuere cubilia', 4),
    ('XnKB6kBrsk', 'luctus et', 9),
    ('XnKB6kBrsk', 'nisi venenatis', 13),
    ('CHgTNybOOK', 'eget', 9),
    ('CHgTNybOOK', 'duis bibendum felis', 10),
    ('CHgTNybOOK', 'pede posuere nonummy', 13),
    ('CHgTNybOOK', 'eu nibh', 14),
    ('CHgTNybOOK', 'rutrum', 18),
    ('CHgTNybOOK', 'nulla suscipit ligula', 22),
    ('CHgTNybOOK', 'sagittis', 24),
    ('pL5YO4V8cg', 'sagittis', 24),
    ('pL5YO4V8cg', 'rutrum', 18),
    ('cea8RZosmz',  null, null),
    ('rmj1faqoXl', 'pede posuere nonummy', 13),
    ('rmj1faqoXl', 'dignissim', 12),
    ('rmj1faqoXl', 'integer ac', 16),
    ('0fPsSWTnz4', 'in blandit', 16),
    ('0fPsSWTnz4', 'vulputate luctus', 19),
    ('0fPsSWTnz4', 'bibendum', 95),
    ('nOg4iT34TL', 'eu nibh', 14),
    ('wIMkXD9AAz', 'eleifend quam', 31),
    ('wIMkXD9AAz', 'diam', 44),
    ('wIMkXD9AAz', 'quis lectus suspendisse', 48),
    ('wIMkXD9AAz', 'ultrices', 50),
    ('avhrB429Mr', 'donec ut', 50),
    ('avhrB429Mr', 'cubilia', 55),
    ('27YKVtYhpn',  null, null),
    ('oCSHyvTtRP', 'nec nisi', 59),
    ('oCSHyvTtRP', 'sagittis', 24),
    ('oCSHyvTtRP', 'integer ac', 16),
    ('gIVfB3wkgn', 'eleifend quam', 31),
    ('gIVfB3wkgn', 'vestibulum vestibulum', 63),
    ('gIVfB3wkgn', 'sg4mi', 65),
    ('gIVfB3wkgn', 'mafia', 69),
    ('gIVfB3wkgn', 'nisi', 71),
    ('UbiiTIyTJS', 'dignissim', 12),
    ('49ILNbEFEH', 'sapien', 74),
    ('49ILNbEFEH', 'justo pellentesque viverra', 76),
    ('49ILNbEFEH', 'dui vel nisl', 78),
    ('49ILNbEFEH', 'bibendum', 95),
    ('GhL2Kx4yti', 'vulputate luctus', 19),
    ('GhL2Kx4yti', 'ultrices', 50),
    ('oGjoGgRa2U', 'dui vel nisl', 78),
    ('oGjoGgRa2U', 'eget', 79),
    ('oGjoGgRa2U', 'penatibus', 81),
    ('1jGL0GxHvJ', 'leo', 82),
    ('1jGL0GxHvJ', 'morbi', 86),
    ('1jGL0GxHvJ', 'eu', 88),
    ('1jGL0GxHvJ', 'justo pellentesque', 90),
    ('jQ5z5X1KRK', 'eu', 88),
    ('tjbKWeNEnh', 'sg4mi', 65),
    ('H51uTmLAjc', 'justo pellentesque viverra', 76),
    ('H51uTmLAjc', 'leo', 82),
    ('lT1HMciH1s', 'morbi', 86),
    ('ffjvxGTJea', 'justo pellentesque', 90),
    ('TLDA9noEnV', 'facilisi', 91);