CREATE TABLE Podcast (
    podcast_id SERIAL primary key,
	nome_podcast VARCHAR(30),
	podcaster VARCHAR(50),
	info VARCHAR(100),
	FOREIGN KEY (podcaster) REFERENCES Podcaster(mail)
);
TRUNCATE ONLY Podcast
RESTART IDENTITY;


insert into Podcast (nome_podcast, podcaster, info) values 
    ('id justo sit', 'cyate3@uol.com.br', 'Right-sized discrete project'),
    ('tellus', 'cyate3@uol.com.br', 'Optimized content-based success'),
    ('phasellus', 'mroelofs5@acquirethisname.com', 'Horizontal mobile hierarchy'),
    ('augue luctus tincidunt', 'xseage8@ibm.com', 'Synergized non-volatile local area network'),
    ('vivamus vestibulum sagittis', 'mscanderet9@google.pl', 'Compatible directional concept'),
    ('ac neque', 'dconkiea@digg.com', 'Fully-configurable stable time-frame'),
    ('nulla integer pede', 'dconkiea@digg.com', 'Implemented static firmware'),
    ('at vulputate vitae', 'zfluryb@yellowbook.com', 'Vision-oriented zero defect model'),
    ('vitae ipsum aliquam', 'dsandsallanc@diigo.com', 'Open-architected system-worthy help-desk'),
    ('faucibus orci', 'zfluryb@yellowbook.com', 'Multi-lateral local toolset'),
    ('vitae ipsum', 'robradaned@va.gov', 'Inverse non-volatile groupware'),
    ('porttitor lorem', 'jsmalef@devhub.com', 'Business-focused needs-based complexity'),
    ('suspendisse', 'kgauchh@paypal.com', 'Mandatory clear-thinking array'),
    ('lacinia', 'grougheyj@photobucket.com', 'Balanced upward-trending adapter'),
    ('in consequat ut', 'grougheyj@photobucket.com', 'Proactive responsive structure'),
    ('feugiat non', 'nbole0@yale.edu', 'Reduced bi-directional local area network'),
    ('sem', 'mcristofarik@123-reg.co.uk', 'Focused web-enabled task-force'),
    ('sapien', 'snottlem@marriott.com', 'Enhanced 4th generation secured line'),
    ('nec dui', 'nbole0@yale.edu', 'Multi-tiered bandwidth-monitored internet solution'),
    ('nibh', 'bjolln@sun.com', 'Realigned 24 hour time-frame'),
    ('diam neque vestibulum', 'kgauchh@paypal.com', 'Down-sized attitude-oriented service-desk'),
    ('sed nisl nunc', 'dmilvarnie1@desdev.cn', 'Open-architected scalable firmware'),
    ('est congue', 'alissendenx@over-blog.com', 'Polarised 6th generation data-warehouse'),
    ('leo', 'jsmalef@devhub.com', 'Business-focused asynchronous definition'),
    ('sapien', 'astiegaro@google.ru', 'Cloned mobile access'),
    ('ac tellus', 'bjolln@sun.com', 'Cross-platform zero tolerance neural-net'),
    ('quis lectus', 'dmilvarnie1@desdev.cn', 'Adaptive reciprocal matrix'),
    ('dui', 'fpiffp@ebay.co.uk', 'Open-source next generation hub'),
    ('pharetra magna', 'mjeremaesq@nytimes.com', 'Enterprise-wide demand-driven forecast'),
    ('amet justo morbi', 'lisaak2@cnet.com', 'Pre-emptive dynamic product'),
    ('leo maecenas', 'rschoberr@51.la', 'Devolved optimal encoding'),
    ('quis', 'ewhates@noaa.gov', 'Networked clear-thinking Graphical User Interface'),
    ('dis', 'kbugsg@nature.com', 'Fully-configurable zero administration migration'),
    ('faucibus orci', 'wsidnellu@hp.com', 'Vision-oriented 24/7 paradigm'),
    ('pharetra', 'wsidnellu@hp.com', 'Exclusive bandwidth-monitored knowledge user'),
    ('a ipsum', 'bmurkusv@hostgator.com', 'Reactive holistic analyzer'),
    ('id nisl', 'kmcilwainew@lulu.com', 'Multi-lateral tangible open architecture'),
    ('libero rutrum ac', 'ewhates@noaa.gov', 'Team-oriented user-facing orchestration'),
    ('eu nibh', 'chardeyy@earthlink.net', 'Synergistic modular paradigm'),
    ('magna vulputate luctus', 'chardeyy@earthlink.net', 'Inverse local structure'),
    ('ante', 'asleneyz@wordpress.com', 'Synergized object-oriented challenge'),
    ('sit', 'eashmore10@arizona.edu', 'Self-enabling holistic ability'),
    ('ultrices', 'uhulburt11@qq.com', 'Streamlined transitional infrastructure'),
    ('diam vitae', 'mroelofs5@acquirethisname.com', 'Grass-roots dedicated support'),
    ('in', 'robradaned@va.gov', 'Profound bandwidth-monitored moderator'),
    ('cursus vestibulum proin', 'kbugsg@nature.com', 'Right-sized real-time moderator'),
    ('consequat', 'uhulburt11@qq.com', 'Realigned zero defect architecture'),
    ('suscipit a feugiat', 'eashmore10@arizona.edu', 'Visionary bottom-line frame'),
    ('turpis a', 'scovil12@pen.io', 'Realigned systemic structure'),
    ('mauris sit', 'asalvadori13@princeton.edu', 'Reactive zero defect projection'),
    ('dolor vel', 'crickersy14@printfriendly.com', 'Advanced bottom-line benchmark'),
    ('vulputate luctus', 'kkimmons15@wikispaces.com', 'Managed optimizing product'),
    ('enim', 'asalvadori13@princeton.edu', 'Synchronised full-range database'),
    ('tortor eu', 'mmaywarde@prweb.com', 'Advanced secondary throughput'),
    ('cras non velit', 'mjeremaesq@nytimes.com', 'Total coherent customer loyalty'),
    ('at feugiat non', 'snottlem@marriott.com', 'Balanced optimal local area network'),
    ('blandit non', 'kmcilwainew@lulu.com', 'Innovative responsive encryption'),
    ('dapibus dolor', 'scovil12@pen.io', 'Integrated heuristic focus group'),
    ('velit eu', 'mmaywarde@prweb.com', 'Business-focused interactive contingency'),
    ('ut', 'csillitoi@acquirethisname.com', 'Exclusive static hierarchy'),
    ('cum sociis', 'scastellan16@google.fr', 'Cross-group intermediate challenge'),
    ('consequat metus sapien', 'econnick17@simplemachines.org', 'Fundamental real-time installation'),
    ('eget rutrum at', 'sdeinhardt18@goo.gl', 'Pre-emptive next generation methodology'),
    ('nullam varius nulla', 'kkimmons15@wikispaces.com', 'Progressive zero defect throughput'),
    ('montes nascetur', 'bjolln@sun.com', 'Automated incremental focus group'),
    ('sit amet', 'xseage8@ibm.com', 'Versatile systematic parallelism'),
    ('sed lacus', 'ffairman19@tripod.com', 'Open-architected 24 hour benchmark'),
    ('imperdiet', 'mcallen6@taobao.com', 'Open-source fresh-thinking open architecture'),
    ('ipsum', 'scastellan16@google.fr', 'Automated discrete local area network'),
    ('sit amet consectetuer', 'asleneyz@wordpress.com', 'Re-engineered web-enabled hierarchy'),
    ('odio', 'olefeaver1a@wordpress.org', 'Seamless intangible task-force'),
    ('vestibulum sit', 'mcristofarik@123-reg.co.uk', 'Enhanced intangible forecast'),
    ('fusce lacus', 'sdeinhardt18@goo.gl', 'Switchable system-worthy internet solution'),
    ('eros elementum pellentesque', 'econnick17@simplemachines.org', 'Reactive actuating synergy'),
    ('sapien', 'dsandsallanc@diigo.com', 'Decentralized bi-directional ability'),
    ('diam neque', 'astiegaro@google.ru', 'Focused zero tolerance algorithm'),
    ('semper interdum', 'mscreas1d@dion.ne.jp', 'Polarised uniform emulation'),
    ('turpis', 'ffairman19@tripod.com', 'Centralized neutral pricing structure'),
    ('rutrum', 'mcallen6@taobao.com', 'Stand-alone zero administration framework'),
    ('in magna bibendum', 'cyate3@uol.com.br', 'Fundamental system-worthy framework'),
    ('integer', 'fchint@1und1.de', 'Secured client-driven infrastructure'),
    ('turpis donec', 'crickersy14@printfriendly.com', 'Networked hybrid parallelism'),
    ('leo', 'achalcraftl@washington.edu', 'Horizontal needs-based moderator'),
    ('enim lorem', 'achalcraftl@washington.edu', 'Phased zero tolerance emulation'),
    ('lobortis', 'mscreas1d@dion.ne.jp', 'Customizable regional artificial intelligence'),
    ('in hac habitasse', 'bjolln@sun.com', 'Secured solution-oriented portal'),
    ('donec', 'csillitoi@acquirethisname.com', 'Monitored systemic matrix'),
    ('interdum mauris ullamcorper', 'chardeyy@earthlink.net', 'Synchronised scalable hardware'),
    ('lobortis vel dapibus', 'nnisot1c@unblog.fr', 'Business-focused cohesive interface'),
    ('purus eu', 'mdorrance1b@github.com', 'Diverse grid-enabled approach'),
    ('vel augue', 'bmurkusv@hostgator.com', 'Exclusive mission-critical function'),
    ('curae', 'mscanderet9@google.pl', 'Ergonomic empowering initiative'),
    ('penatibus et magnis', 'olefeaver1a@wordpress.org', 'Re-contextualized disintermediate solution'),
    ('phasellus id sapien', 'alissendenx@over-blog.com', 'Open-architected well-modulated info-mediaries'),
    ('luctus nec', 'fchint@1und1.de', 'Digitized executive migration'),
    ('nulla mollis molestie', 'jsmalef@devhub.com', 'Business-focused foreground leverage'),
    ('nascetur ridiculus', 'nnisot1c@unblog.fr', 'Right-sized logistical complexity'),
    ('augue luctus tincidunt', 'rschoberr@51.la', 'Down-sized exuding contingency'),
    ('justo', 'mdorrance1b@github.com', 'Grass-roots contextually-based hardware'),
    ('nascetur ridiculus mus', 'lisaak2@cnet.com', 'Quality-focused uniform knowledge base');