CREATE DATABASE streaming_platform
    WITH 
    OWNER = sebastianosanson
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

--table utente
DROP TABLE IF EXISTS Utente CASCADE;

CREATE TABLE Utente (
	mail varchar (50) primary key,
	nome varchar (50),
	cognome varchar (50),
	stato char (2),
	password varchar (30) not null,
	nickname varchar (20) not null,
	followers int,
	following int
);

insert into Utente (mail, nome, cognome, stato, password, nickname, followers, following) values 
('msier0@fotki.com', 'Malinda', 'Sier', 'HK', '0PwstJO', 'msier0', 19, 684),
('aabbie1@goodreads.com', 'Aprilette', 'Abbie', 'CN', 'VSdEPik4d6T', 'aabbie1', 446, 72),
('dscholfield2@opera.com', 'Donal', 'Scholfield', 'PT', 'J0oX2Do', 'dscholfield2', 624, 531),
('pspellacey3@issuu.com', 'Paul', 'Spellacey', 'ID', '5R9Eu6KjLL', 'pspellacey3', 44, 441),
('kmalyj4@adobe.com', 'Kristien', 'Malyj', 'GB', 'VkLWE8', 'kmalyj4', 582, 714),
('tluetkemeyer5@discuz.net', 'Tracey', 'Luetkemeyer', 'BR', 'kKnaQKCW', 'tluetkemeyer5', 915, 401),
('ydorton6@disqus.com', 'Yorgos', 'Dorton', 'ID', 'pyyMH5T5aOu', 'ydorton6', 911, 965),
('jgaythwaite7@whitehouse.gov', 'Joycelin', 'Gaythwaite', 'GM', 'k0tSxW', 'jgaythwaite7', 915, 699),
('ksecret8@t-online.de', 'Kimbra', 'Secret', 'JP', '7g1Auwl5g', 'ksecret8', 50, 354),
('iespy9@reuters.com', 'Ingar', 'Espy', 'RU', 'mZxivT8m', 'iespy9', 365, 977),
('grosenhaupta@jalbum.net', 'Gratia', 'Rosenhaupt', 'UY', 'iTVVXyL', 'grosenhaupta', 717, 485),
('jcriminb@economist.com', 'Jaine', 'Crimin', 'CN', 'zb2FNF8qM', 'jcriminb', 127, 605),
('lshanksc@dropbox.com', 'Lelah', 'Shanks', 'NZ', 'al4cFZ5z', 'lshanksc', 274, 373),
('fnastd@usatoday.com', 'Faber', 'Nast', 'PH', '0sUITas', 'fnastd', 572, 69),
('ogriniove@sakura.ne.jp', 'Oliviero', 'Griniov', 'US', 'fvBTUL2YBP', 'ogriniove', 260, 281),
('afoxallf@twitter.com', 'Ax', 'Foxall', 'BR', 'qB3IPzOQxZN', 'afoxallf', 77, 845),
('ahuycheg@geocities.jp', 'Ambrosius', 'Huyche', 'EC', 'yDstYoby', 'ahuycheg', 419, 183),
('jkermith@wunderground.com', 'Jolee', 'Kermit', 'CN', 'YsT6vDpGwc2M', 'jkermith', 844, 239),
('escoblei@weebly.com', 'Elspeth', 'Scoble', 'CN', 'vAgVdSU', 'escoblei', 663, 881),
('jtimlettj@sourceforge.net', 'Jorey', 'Timlett', 'CN', 'omvdPlrniI', 'jtimlettj', 914, 585),
('wmalyk@hubpages.com', 'Welby', 'Maly', 'ID', 'xtvdl63f', 'wmalyk', 434, 289),
('cmenisl@cdc.gov', 'Cyril', 'Menis', 'CZ', '8QK5SXwaRaVo', 'cmenisl', 772, 885),
('lfollinm@nationalgeographic.com', 'Lorelei', 'Follin', 'RU', '8dZlYRdU9V', 'lfollinm', 919, 771),
('ljowittn@bloglovin.com', 'Leigh', 'Jowitt', 'ID', 'jJCrpHmN', 'ljowittn', 606, 131),
('bwhitmarsho@reference.com', 'Berny', 'Whitmarsh', 'ID', 'WCEWSaZrZ', 'bwhitmarsho', 806, 732),
('jlumlyp@yellowbook.com', 'Janelle', 'Lumly', 'RU', 'UCDMA6LFDYvV', 'jlumlyp', 900, 223),
('zjeppsq@elegantthemes.com', 'Zebulon', 'Jepps', 'ID', 'v39F1SfH', 'zjeppsq', 845, 891),
('hhallorr@house.gov', 'Hermann', 'Hallor', 'CL', 'BR8Y7lTc', 'hhallorr', 113, 321),
('esyslands@dailymail.co.uk', 'Erin', 'Sysland', 'CN', 'ytgRmwJ', 'esyslands', 518, 403),
('darstallt@house.gov', 'Dianna', 'Arstall', 'CA', 'xIYpr3ZEYC', 'darstallt', 48, 38),
('mokelleheru@networkadvertising.org', 'Mikol', 'O'' Kelleher', 'CO', 'qOcTEk6pgjH1', 'mokelleheru', 84, 80),
('lwellerv@huffingtonpost.com', 'Lin', 'Weller', 'CN', 'S3CmhyEC', 'lwellerv', 137, 227),
('lpinkettw@theglobeandmail.com', 'Lacee', 'Pinkett', 'CZ', 'dqMh166V2', 'lpinkettw', 974, 46),
('lboughtflowerx@cdc.gov', 'Lisabeth', 'Boughtflower', 'US', 'EZQfETmIl', 'lboughtflowerx', 869, 323),
('oshankliny@domainmarket.com', 'Oby', 'Shanklin', 'CN', 'uETKvRLC', 'oshankliny', 241, 344),
('gisacqz@google.co.uk', 'Gustave', 'Isacq', 'CN', 'EH524lSWrIc', 'gisacqz', 881, 915),
('bsimoneau10@google.ca', 'Baxter', 'Simoneau', 'RU', 'xnN4etjR', 'bsimoneau10', 767, 56),
('jtayt11@marketwatch.com', 'Janith', 'Tayt', 'PT', '6dwMf1hKeIj', 'jtayt11', 708, 292),
('rolsson12@arizona.edu', 'Raynard', 'Olsson', 'FM', 'F4D3pKSMwZ2', 'rolsson12', 958, 786),
('sblamphin13@yahoo.co.jp', 'Silvanus', 'Blamphin', 'PH', 'V7a54G9TyeU', 'sblamphin13', 359, 753),
('gheatherington14@cloudflare.com', 'Garner', 'Heatherington', 'PH', 'yqUYr9RUPr', 'gheatherington14', 110, 695),
('charbin15@bloglines.com', 'Cammi', 'Harbin', 'ID', 'x1sns19WGh', 'charbin15', 459, 47),
('sduns16@google.com.br', 'Seumas', 'Duns', 'CN', '6HZQwGaMZr5S', 'sduns16', 67, 62),
('hrousel17@nytimes.com', 'Heywood', 'Rousel', 'HU', '9GcK2552', 'hrousel17', 783, 727),
('blandon18@soup.io', 'Briney', 'Landon', 'US', 'N1EJMG', 'blandon18', 327, 81),
('manderbrugge19@vistaprint.com', 'Moss', 'Anderbrugge', 'ID', 'h8eR1D', 'manderbrugge19', 190, 378),
('dcooney1a@drupal.org', 'Dulcy', 'Cooney', 'CN', 'xyIo4UZ', 'dcooney1a', 454, 664),
('lstothert1b@scientificamerican.com', 'Lia', 'Stothert', 'CN', 'wbu61n35lmE', 'lstothert1b', 553, 981),
('charradence1c@friendfeed.com', 'Christy', 'Harradence', 'BR', 'kCQZmAWoX', 'charradence1c', 649, 289),
('ehuxley1d@icq.com', 'Erich', 'Huxley', 'US', 'pP5s1L', 'ehuxley1d', 767, 883),
('cdelleschi1e@nbcnews.com', 'Coleen', 'Delleschi', 'PT', 'rD4l9sVTys', 'cdelleschi1e', 440, 602),
('rneligan1f@kickstarter.com', 'Robinson', 'Neligan', 'UY', 'b3494HRaL', 'rneligan1f', 75, 600),
('brawne1g@mozilla.org', 'Brandea', 'Rawne', 'TH', 'TeU7j2MMd', 'brawne1g', 57, 513),
('escammell1h@rakuten.co.jp', 'Emili', 'Scammell', 'ID', 'Ujivr4nIfY', 'escammell1h', 587, 589),
('wbernucci1i@trellian.com', 'Winni', 'Bernucci', 'JO', '21GnP0tE5', 'wbernucci1i', 549, 577),
('sbeltzner1j@chicagotribune.com', 'Shannan', 'Beltzner', 'SI', 'ReHeytUO9G', 'sbeltzner1j', 414, 893),
('abickerton1k@storify.com', 'Abbie', 'Bickerton', 'RU', 'VybSrm5yMR', 'abickerton1k', 362, 963),
('adargie1l@g.co', 'Ambrose', 'Dargie', 'MX', 'RTKL4U', 'adargie1l', 809, 777),
('owhiffin1m@odnoklassniki.ru', 'Orlando', 'Whiffin', 'CN', 'PuaXiTDsb', 'owhiffin1m', 376, 487),
('dobray1n@topsy.com', 'Dag', 'Obray', 'CN', 'DnkjAwtvIGs', 'dobray1n', 204, 667),
('lgreenley1o@state.tx.us', 'Lorry', 'Greenley', 'BR', 'aZD4FT8', 'lgreenley1o', 87, 542),
('abroadey1p@toplist.cz', 'Agustin', 'Broadey', 'ID', '3t3QyVmDgNc', 'abroadey1p', 641, 954),
('amcgraffin1q@upenn.edu', 'Andriette', 'McGraffin', 'TH', 'mYUL3tydMM35', 'amcgraffin1q', 696, 100),
('jchattoe1r@cdc.gov', 'Jana', 'Chattoe', 'JM', 'lmtljW5', 'jchattoe1r', 227, 87),
('yolkowicz1s@webnode.com', 'Yorgos', 'Olkowicz', 'ID', 'ioJSYSk2GoGU', 'yolkowicz1s', 637, 845),
('cflewitt1t@bloomberg.com', 'Chas', 'Flewitt', 'ID', 'L8r8DrmBp', 'cflewitt1t', 316, 406),
('mlorens1u@pen.io', 'Mimi', 'Lorens', 'FR', 'kWNSEia', 'mlorens1u', 437, 472),
('cianetti1v@yandex.ru', 'Colby', 'Ianetti', 'UA', 'FpGn7mg', 'cianetti1v', 18, 543),
('cholde1w@wikipedia.org', 'Cale', 'Holde', 'ID', 'wUtdzb', 'cholde1w', 448, 395),
('fflewett1x@loc.gov', 'Fletch', 'Flewett', 'VN', 'rFYI4eK4Or', 'fflewett1x', 106, 462),
('awethered1y@globo.com', 'Agretha', 'Wethered', 'CN', '9wQmzxQV', 'awethered1y', 901, 92),
('gmcaleese1z@merriam-webster.com', 'Gerta', 'McAleese', 'LV', 't5EgvsFWOy', 'gmcaleese1z', 847, 352),
('lcamelia20@addtoany.com', 'Leif', 'Camelia', 'ID', 'sGcKWEiW5QM', 'lcamelia20', 252, 438),
('asqueers21@statcounter.com', 'Alanson', 'Squeers', 'MZ', 'DjD83bZsy', 'asqueers21', 82, 47),
('abrownlee22@berkeley.edu', 'Adolphus', 'Brownlee', 'KE', 'fmMpU6iKV', 'abrownlee22', 533, 140),
('bdelph23@myspace.com', 'Brittan', 'Delph', 'CN', 'cBg06VsTDsz', 'bdelph23', 366, 604),
('ckiendl24@jigsy.com', 'Caterina', 'Kiendl', 'BR', '9Ys24LZ8NdK', 'ckiendl24', 797, 877),
('dadamo25@sbwire.com', 'Daffi', 'Adamo', 'ES', 'nuUnqoIV9F', 'dadamo25', 42, 693),
('sparade26@domainmarket.com', 'Stephi', 'Parade', 'CN', 'RwnV6Z', 'sparade26', 38, 796),
('dtipping27@vkontakte.ru', 'Daisey', 'Tipping', 'CN', 'gvgWT3SL', 'dtipping27', 73, 505),
('rbeswell28@netscape.com', 'Roselia', 'Beswell', 'RU', 'n1qVE8', 'rbeswell28', 363, 437),
('ishimwell29@typepad.com', 'Ira', 'Shimwell', 'RU', 'vlCqY86rCFfA', 'ishimwell29', 60, 246),
('kbillborough2a@gmpg.org', 'Karlotte', 'Billborough', 'ID', 'VeIDmzcdiZ8G', 'kbillborough2a', 715, 808),
('cpetran2b@blog.com', 'Cherilynn', 'Petran', 'CN', 'ESoTruEPsEu', 'cpetran2b', 114, 234),
('mbrewster2c@google.co.uk', 'Meagan', 'Brewster', 'BR', 'Xeqb1wbPMdpY', 'mbrewster2c', 7, 562),
('lpynn2d@last.fm', 'Lombard', 'Pynn', 'GR', 'lVoCHih', 'lpynn2d', 817, 650),
('lkinglesyd2e@vk.com', 'Lynnea', 'Kinglesyd', 'CN', 'JgDYzasL8', 'lkinglesyd2e', 645, 66),
('fluciano2f@shareasale.com', 'Fredek', 'Luciano', 'CN', 'JKE79oOaH1zi', 'fluciano2f', 516, 455),
('lrabbe2g@godaddy.com', 'Link', 'Rabbe', 'PH', 'OJ9Iq0TWQw', 'lrabbe2g', 111, 308),
('ehawkswood2h@google.co.uk', 'Elvera', 'Hawkswood', 'US', '1iUCWiQgQYx', 'ehawkswood2h', 53, 781),
('jcockings2i@sun.com', 'Joy', 'Cockings', 'FR', 'Qo6xpt', 'jcockings2i', 818, 654),
('pbysh2j@de.vu', 'Patrizius', 'Bysh', 'MM', '9ExNUwpnCg', 'pbysh2j', 753, 111),
('dgeorgius2k@miibeian.gov.cn', 'Demott', 'Georgius', 'PY', '1AdfgKBR', 'dgeorgius2k', 363, 896),
('glyte2l@oakley.com', 'Garret', 'Lyte', 'RU', 'lOzU3cbW0UCt', 'glyte2l', 125, 606),
('mgorton2m@angelfire.com', 'Maison', 'Gorton', 'EE', 'ZJyz0l2', 'mgorton2m', 486, 701),
('cpickersgill2n@oaic.gov.au', 'Catherin', 'Pickersgill', 'PH', 'vZ76F1MItNqt', 'cpickersgill2n', 617, 191),
('nrogerson2o@sitemeter.com', 'Neila', 'Rogerson', 'BR', '2MT9J445A0v', 'nrogerson2o', 989, 632),
('rpetrolli2p@apache.org', 'Ramonda', 'Petrolli', 'ID', 'LHWkD71', 'rpetrolli2p', 785, 984),
('ifocke2q@wp.com', 'Igor', 'Focke', 'CN', 'zKgDVXYL', 'ifocke2q', 650, 908),
('dcolclough2r@issuu.com', 'Dannye', 'Colclough', 'ID', 'TRjj2qy6g', 'dcolclough2r', 323, 670);
                          
